targets:
  prod:
    permissions:
      - user_name: rohit.mathw@gmail.com
        level: CAN_RUN
      - user_name: rohit.mathw@gmail.com
        level: CAN_VIEW
    
    variables:
      catalog: ctlg_rm_dev_ext